FROM lukemathwalker/cargo-chef AS planner
WORKDIR app
COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM lukemathwalker/cargo-chef AS cacher
WORKDIR app
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM rust:1.52-slim-buster AS builder
WORKDIR app
COPY . .
# Copy over the cached dependencies
COPY --from=cacher /app/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
RUN cargo build

FROM debian:buster-slim
COPY --from=builder /app/target/debug/matchhostfsowner /sbin/matchhostfsowner
ENTRYPOINT ["/sbin/matchhostfsowner"]
