FROM rust:1.57-slim-buster AS builder
WORKDIR app
COPY Cargo.toml Cargo.lock .

# Build dependencies with cache
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    mkdir src && \
    echo "fn main() {println!(\"if you see this, the build broke\")}" > src/main.rs && \
    cargo build && \
    rm -rf src

# Now build our own sources, also with cache
COPY src src
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    touch src/main.rs && \
    cargo build


FROM debian:buster-slim
COPY --from=builder /app/target/debug/matchhostfsowner /sbin/matchhostfsowner
# Redirect stderr to stdout so that — if the container is started in the background with 'docker run -d' —
# stdout and stderr data don't get interleaved wrongly in 'docker logs' output.
ENTRYPOINT ["/bin/sh", "-c", "exec /sbin/matchhostfsowner \"$@\" 2>&1", "-"]
